version: '3'
services:

  webapp:
    build:
      context: .
      dockerfile: Dockerfile.webapp2
    working_dir: /webapp
    entrypoint: /usr/local/bin/php-fpm.sh
    environment:
      - APP_ENV=local
      - PASSPORT_PUBLIC_KEY
      - PASSPORT_PRIVATE_KEY
    volumes:
      - webapp:/webapp
      - webapp/.env.docker:/webapp/.env

volumes:
  webapp:
    driver_opts:
      type: none
      device: .
      o: bind