version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.webapp1
    working_dir: //var/www
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./.env.docker:/var/www/html/.env
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
