FROM nginx:latest

COPY ./containers/nginx/nginx.conf  /etc/nginx/nginx.coN
COPY ./containers/nginx/default.conf  /etc/nginx/conf.d/default.conf
COPY ./containers/nginx/webapp.conf /etc/nginx/conf.d/webapp.conf

EXPOSE 8080
