version: '3'
services:

  webapp:
    build:
      context: .
      dockerfile: Dockerfile.webapp3
    working_dir: /webapp
    entrypoint: /usr/local/bin/php-fpm.sh
    environment:
      - APP_ENV=local
      - PASSPORT_PUBLIC_KEY
      - PASSPORT_PRIVATE_KEY
    volumes:
      - ./:/var/www/html
      # - ./.env.docker:/var/www/html/.env
      # # - .env.docker:/webapp/.env
      # - .gitignore:/webapp/.gitignore
      # - webapp:/webapp

# volumes:
#   webapp:
#     driver_opts:
#       type: none
#       device: .
#       o: bind